### ISSUE TITLE
CloverExtractor fails to build  AudioPkg.

### ISSUE THREAD

**Issue by ReddestDream** [corpnewt/CloverExtractor#4] opened 2019-10-17 01:45 UTC
Got message: Failed to build AudioPkg! during Clover building process.

Not that I use it. Just thought I'd let you know. ;p

**Comment by corpnewt** [comment] 2019-10-17 17:13
Yeah - the same happened to me, I just run the macbuild.tool within the project though, so my guess is something else may be amiss as the other .efi drivers build as intended.  I'll do some digging when I have time and see if I can figure out why.

-CorpNewt

**Comment by corpnewt** [comment] 2019-10-17 18:38
Should be fixed in [this commit](https://github.com/corpnewt/CloverExtractor/commit/4bdc11d13184396037591872dd52dd92e1a71d51).  You'll likely need to wipe the EFI driver sources before it'll take effect (`WE.  Wipe Only EFI Driver Source Folders` in the main menu).

-CorpNewt

**Closed as completed by corpnewt** 2019-10-17 18:38 UTC
